name:                CS8-AMV-project
version:             0.1.0.0
license:             BSD3
author:              "Robert Banu & Jesse van der Velden"
maintainer:          "r.banu@student.utwente.nl, j.vandervelden@student.utwente.nl"
copyright:           "2019 Robert Banu & Jesse van der Velden"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.

dependencies:
- base >= 4.7 && < 5
- parsec
- sprockell

library:
  source-dirs: src

executables:
  project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CS8-AMV-project

tests:
  project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CS8-AMV-project
